apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: oauthful
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oauthful
  template:
    metadata:
      labels:
        app: oauthful
    spec:
{{ if .gke_nodepool }}
      nodeSelector:
        cloud.google.com/gke-nodepool: {{ .gke_nodepool }}
{{ end }}
      containers:
      - name: app
        image: "opensourcefoundries/oauthful:6ca0e25"
        ports:
        - containerPort: 8000
        env:
        - name: USER_MODULE
          value: oauthful.user:FauxUser
---

apiVersion: v1
kind: Service
metadata:
  name: oauthful
spec:
  ports:
  - targetPort: 8000
    port: 80
  selector:
    app: oauthful
